### ISSUE TITLE
The definition or description of all labels

### ISSUE THREAD

**Issue by Zhaoxuanqin** [nlpaueb/finer#2]
Hi,
This is an awesome dataset, while the labels are complicated to understand especially for those who are not very familiar with financial field. Are you able to please provide some materials such as website page or text document for definition or description of labels. Thanks  
in advance !

**Comment by lefterisloukas** [comment]
The labels used come from XBRL. Here is their site: https://xbrl.us/home/filers/sec-reporting/taxonomies/
