### ISSUE TITLE
Pretrained weights for finer-139

### ISSUE THREAD

**Issue by Jinsu-L** [nlpaueb/finer#3]
Thank you for sharing your dataset and SEC_BERT model with huggingface.

I'm asking because I can't find the weights of the model trained on Finer-139 on huggingface or github.

Can I get pretrained weights in SEC-BERT for finer-139?

Thanks
in advance !

**Comment by Rhtyme** [comment]
Check their hugging face page: https://huggingface.co/nlpaueb

**Comment by lefterisloukas** [comment]
The pre-trained models are at https://huggingface.co/nlpaueb/sec-bert-base
https://huggingface.co/nlpaueb/sec-bert-num
https://huggingface.co/nlpaueb/sec-bert-shape

You still need to fine-tune them. We did not keep the checkpoints of the fine-tuned models, but we have all the available hyperparameters in the paper if you want to reproduce the experiments.
